from manim import *

class function_2(Scene):
    def construct(self):

        #辅助工具
        '''plane = NumberPlane()
        self.add(plane)'''
        
        #开场白
        intro_text_1 = MathTex(
            "(a-b)^{2} = a^{2}-2ab+b^{2}"
        )
        intro_text_2 = MathTex(
            '?'
        )
        self.play(Write(intro_text_1))
        self.wait(0.5)
        intro_text_2.shift(1*DOWN)
        self.play(Write(intro_text_2))
        self.wait(1)
        self.play(Unwrite(intro_text_1),Unwrite(intro_text_2))
        self.wait(0.5)
        
        #大正方形的边框绘制
        huge_square = Square().scale(3)
        self.play(Create(huge_square),rate_func=smooth)
        self.wait(0.5)

        #提示大正方形的面积&标注a
        t_1 = MathTex("a^{2}",font_size=80)
        t_2 = MathTex("a",font_size=80)
        t_3 = MathTex("a",font_size=80)
        t_2.shift(3.5*UP)
        t_3.shift(3.5*RIGHT)
        self.play(Write(t_1))
        self.wait(0.5)
        remind_line_1 = Line().scale(3)
        remind_line_2 = Line().scale(3)
        remind_line_2.rotate(90*DEGREES,OUT)
        remind_line_1.shift(3.*UP)
        remind_line_2.shift(3.*RIGHT)
        self.play(Indicate(remind_line_1),scale_factor=1.1)
        self.play(Indicate(remind_line_2),scale_factor=1.1)
        self.wait(0.5)
        self.play(Write(t_2))
        self.play(Write(t_3))
        self.wait(0.5)
        self.play(Unwrite(t_1))
        self.wait(0.5)
        
        #分割线的绘制
        cut_line_1=Line().scale(3)
        cut_line_2=Line().scale(3)
        cut_line_1.rotate(-90*DEGREES,IN)
        cut_line_1.shift(1.5*RIGHT)
        cut_line_2.shift(1.5*UP)
        self.play(Create(cut_line_1),Create(cut_line_2),rate_func=smooth)
        self.wait(0.5)
        
        #大正方形的区域上色
        square_a2 = Square(fill_color=BLUE,fill_opacity=0.5).scale(2.25)
        square_a2.shift(0.75*DOWN+0.75*LEFT)
        square_b2 = Square(fill_color=RED,fill_opacity=0.5).scale(0.75)
        square_b2.shift(2.25*UP+2.25*RIGHT)
        rect_ab_1 = Rectangle(height=1.5,width=4.5,fill_color=YELLOW,fill_opacity=0.5)
        rect_ab_1.shift(2.25*UP+0.75*LEFT)
        rect_ab_2 = rect_ab_1.copy()
        rect_ab_2.rotate(90*DEGREES,OUT)
        rect_ab_2.shift(3*RIGHT,3*DOWN)
        self.play(FadeIn(square_a2,square_b2,rect_ab_1,rect_ab_2),rate_func=smooth)
        self.wait(0.5)

        #提示小正方形的面积&标注b
        t_4 = MathTex(
            "b^2"
        )
        t_4.shift(2.25*RIGHT+2.25*UP)
        self.play(Write(t_4))
        self.wait(0.5)
        remind_line_3 = Line().scale(0.75)
        remind_line_4 = Line().scale(0.75)
        remind_line_3.shift(3*UP+2.25*RIGHT)
        remind_line_4.rotate(90*DEGREES,IN)
        remind_line_4.shift(2.25*UP+3*RIGHT)
        self.play(Indicate(remind_line_3),scale_factor=1.1)
        self.play(Indicate(remind_line_4),scale_factor=1.1)
        self.wait(0.5)
        t_6 = MathTex("b",font_size=60)
        t_7 = t_6.copy()
        t_6.shift(3.5*RIGHT+2.25*UP)
        t_7.shift(2.25*RIGHT+3.5*UP)
        self.play(Write(t_6),Write(t_7))
        self.wait(0.5)
        self.play(Unwrite(t_4))
        self.wait(0.5)

        #高亮&标注a-b
        remind_line_1.set_z_index(1)
        self.play(Indicate(remind_line_1),Indicate(t_2))
        self.wait(0.5)
        remind_line_3.set_z_index(2)
        self.play(Indicate(remind_line_3),Indicate(t_7))
        self.wait(0.5)
        remind_line_5 = Line().scale(2.25)
        remind_line_5.shift(3*UP+0.75*LEFT)
        remind_line_5.set_z_index(3)
        t_8 = MathTex("a-b",font_size=60)
        t_8.next_to(remind_line_5,DOWN)
        t_8.shift(0.15*UP)
        t_9 = MathTex("a-b",font_size=60)
        self.play(Indicate(remind_line_5))
        self.play(Write(t_8),run_time=1)
        self.wait(0.5)
        remind_line_5.generate_target()
        remind_line_5.target.shift(1.5*DOWN)
        self.play(MoveToTarget(remind_line_5))
        self.wait(0.5)
        t_9.next_to(remind_line_5,DOWN)
        t_9.shift(0.15*UP)
        self.play(Unwrite(t_8))
        self.wait(0.1)
        self.play(Write(t_9))
        self.wait(0.75)

        #同理可得a-b
        self.play(Rotating(remind_line_5,radians=90*DEGREES,axis=OUT,about_point=1.5*UP+1.5*RIGHT),run_time=1) 
        self.wait(0.5)
        t_10 = t_9.copy()
        t_10.next_to(remind_line_5,LEFT)
        t_10.shift(0.15*RIGHT)
        self.play(Write(t_10))
        self.wait(0.5)

        #辅助图形整体位移
        whole = VGroup(huge_square,t_1,t_2,t_3,t_4,t_6,t_7,t_8,t_9,t_10,remind_line_1,remind_line_2,remind_line_3,remind_line_4,remind_line_5,cut_line_1,cut_line_2,square_a2,square_b2,rect_ab_1,rect_ab_2)
        self.play(whole.animate.shift(1.5*UP+4*LEFT).scale(0.5))
        self.wait(0.5)

        #面积图形等式
        t_10_1 = MathTex("area",font_size=60)
        t_10_1.shift(2*DOWN+5*LEFT)
        t_11 = MathTex('=',font_size=60)
        t_12 = MathTex('-',font_size=60)
        t_13 = t_10_1.copy()
        t_14 = t_10_1.copy()
        t_15 = t_10_1.copy()
        t_16 = MathTex('-',font_size=60)
        self.play(Write(t_10_1))
        square_a2_copy = square_a2.copy()
        square_a2_copy.generate_target()
        square_a2_copy.target.scale(0.25).next_to(t_13,RIGHT)
        self.play(MoveToTarget(square_a2_copy))
        self.wait(0.5)
        t_11.next_to(square_a2_copy,RIGHT)
        self.play(Write(t_11))
        t_13.next_to(t_11,RIGHT)
        self.play(Write(t_13))
        huge_square_copy = huge_square.copy()
        huge_square_copy.generate_target()
        huge_square_copy.target.scale(0.25).next_to(t_13,RIGHT)
        self.play(MoveToTarget(huge_square_copy))
        self.wait(0.5)
        t_12.next_to(huge_square_copy,RIGHT)
        self.play(Write(t_12))
        t_14.next_to(t_12,RIGHT)
        self.play(Write(t_14))
        rect_ab_1_copy = rect_ab_1.copy()
        rect_ab_2_copy = rect_ab_2.copy()
        rect_ab_1_copy.generate_target()
        rect_ab_2_copy.generate_target()
        rect_ab_1_copy.target.rotate(90*DEGREES,OUT).scale(0.25).next_to(t_14,RIGHT)
        rect_ab_2_copy.target.scale(0.25).next_to(rect_ab_1_copy.target,RIGHT)
        self.play(MoveToTarget(rect_ab_1_copy),MoveToTarget(rect_ab_2_copy))
        self.wait(0.5)
        t_16.next_to(rect_ab_2_copy,RIGHT)
        self.play(Write(t_16))
        t_15.next_to(t_16,RIGHT)
        self.play(Write(t_15))
        square_b2_copy = square_b2.copy()
        square_b2_copy.generate_target()
        square_b2_copy.target.scale(0.35).next_to(t_15,RIGHT)
        self.play(MoveToTarget(square_b2_copy))
        self.wait(0.75)

        #面积转换公式
        first_group = VGroup(t_10_1,square_a2_copy)
        second_group = VGroup(t_13,huge_square_copy)
        third_group = VGroup(t_14,rect_ab_1_copy,rect_ab_2_copy)
        fourth_group = VGroup(t_15,square_b2_copy)
        final_tex_1 = MathTex("(a-b)^{2}")
        final_tex_1.next_to(t_11,LEFT)
        final_tex_2 = MathTex("a^{2}")
        final_tex_2.next_to(t_11,RIGHT)
        final_tex_2.shift(0.07*UP)
        final_tex_3 = MathTex("2[(a-b)b]")
        final_tex_3.next_to(t_12,RIGHT)
        final_tex_4 = MathTex("b^{2}")
        final_tex_4.next_to(t_16,RIGHT)
        final_tex_4.shift(0.05*UP)
        self.play(Indicate(square_a2),scale_factor=1.1)
        self.play(ReplacementTransform(first_group,final_tex_1))
        self.wait(0.25)
        self.play(Indicate(huge_square),scale_factor=1.1)
        self.play(ReplacementTransform(second_group,final_tex_2))
        self.wait(0.25)
        self.play(Indicate(rect_ab_1),Indicate(rect_ab_2),scale_factor=1.1)
        self.play(ReplacementTransform(third_group,final_tex_3))
        self.wait(0.25)
        self.play(Indicate(square_b2),scale_factor=1.1)
        self.play(ReplacementTransform(fourth_group,final_tex_4))
        self.wait(0.5)

        #公式移动&辅助图消失
        small_group_1 = VGroup(t_12,final_tex_3)
        small_group_2 = VGroup(t_16,final_tex_4)
        small_group_1.generate_target()
        small_group_2.generate_target()
        small_group_1.target.next_to(final_tex_2,RIGHT)
        self.play(MoveToTarget(small_group_1))
        small_group_2.target.next_to(small_group_1,RIGHT)
        self.play(MoveToTarget(small_group_2))
        method = VGroup(final_tex_1,t_11,final_tex_2,small_group_1,small_group_2)
        method.generate_target()
        method.target.shift(2.25*UP,1.75*RIGHT)
        self.play(FadeOut(whole),MoveToTarget(method))
        self.wait(1)

        #公式化简
        clean_group_1 = MathTex("2b(a-b)")
        clean_group_1.next_to(t_12,RIGHT)
        clean_group_2_1 = MathTex("(2ab")
        clean_group_2_2 = MathTex('-',font_size=60)
        clean_group_2_3 = MathTex("2b^{2})")
        clean_group_2_1.next_to(t_12,RIGHT)
        clean_group_2_2.next_to(clean_group_2_1,RIGHT)
        clean_group_2_3.next_to(clean_group_2_2,RIGHT)
        clean_group_2_1.shift(0.01*DOWN)
        clean_group_2 = VGroup(clean_group_2_1,clean_group_2_2,clean_group_2_3)
        move_group_1 = VGroup(t_16,final_tex_4)
        clean_group_3_1 = MathTex("2ab")
        clean_group_3_2 = MathTex("+")
        clean_group_3_3 = MathTex("2b^{2}")
        clean_group_3_1.next_to(t_12,RIGHT)
        clean_group_3_2.next_to(clean_group_3_1,RIGHT)
        clean_group_3_3.next_to(clean_group_3_2,RIGHT)
        clean_group_3 = VGroup(clean_group_3_1,clean_group_3_2,clean_group_3_3)
        clean_group_3.next_to(t_12,RIGHT)
        clean_group_4 = VGroup(clean_group_3_3,t_16,final_tex_4)
        SpecialText = MathTex("b^2")
        SpecialText.next_to(clean_group_3_2,RIGHT)
        SpecialText.shift(0.01*UP)
        self.play(ReplacementTransform(final_tex_3,clean_group_1))
        self.wait(0.5)
        self.play(ReplacementTransform(clean_group_1,clean_group_2),move_group_1.animate.shift(0.45*RIGHT))
        self.wait(0.5)
        self.play(ReplacementTransform(clean_group_2,clean_group_3),move_group_1.animate.shift(0.45*LEFT))
        self.wait(0.5)
        self.play(ReplacementTransform(clean_group_4,SpecialText))
        self.wait(1)

